### ISSUE TITLE
Remove AccountAlreadyExists error in reply

### ISSUE THREAD

**Issue by bbbbbbboc** [terra-money/warp-contracts#5]
Reminder to delete this error and update unit test since it's unreachable, controller will [return early in `create_account` for addresses already own a warp account](https://github.com/terra-money/warp-contracts/blob/master/contracts/warp-controller/src/execute/account.rs#L23-L29).

[discord discussion](https://discord.com/channels/1045185632873488414/1045185633339052140/1056826107585904681)

**Comment by vladjdk** [comment]
Feel free to submit a PR for this :)
